name: Example Workflow
on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Export variable
        run: echo "MY_VAR=Hello, world!" >> $GITHUB_ENV

      - name: Use exported variable
        run: echo "MY_VAR is $AA"