name: Example Workflow
on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_VAR_C: ${{ vars.C }}  # Using a repository variable
      MY_SECRET_A: ${{ secrets.A }}  # Using a secret
    steps:
      - name: Print Variables
        run: |
          echo "MY_VAR_C: $MY_VAR_C"
          echo "MY_SECRET_A is hidden"