name: Example Workflow
on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_VAR_CC: ${{ vars.CC }}  # Using a repository variable
      MY_SECRET_AA: ${{ secrets.AA }}  # Using a secret
    steps:
      - name: Print Variables
        run: |
          echo "MY_VAR_C: $MY_VAR_C"
          echo "MY_SECRET_A is hidden"